# Lines configured by zsh-newuser-install
HISTFILE=~/.local/state/histfile
HISTSIZE=10000
SAVEHIST=10000
bindkey -v
# End of lines configured by zsh-newuser-install

EDITOR=nvim
VISUAL=nvim

CARGO_HOME=$HOME/.local/share/cargo
RUSTUP_HOME=$HOME/.local/share/rustup

alias ls='ls --color=auto'
alias lg='lazygit'
alias nps='nps -e=true'

function restart-ssh() {
  pkill ssh-agent
  eval "$(ssh-agent -s)"
}

# yazi with cd on exit
function y() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  yazi "$@" --cwd-file="$tmp"
  IFS= read -r -d '' cwd < "$tmp"
  [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
  rm -f -- "$tmp"
}

function rebuild() {
  case "$(hostname -s)" in
    thinkpad)
      sudo nixos-rebuild switch --flake ~/dotfiles/#thinkpad --show-trace
      ;;
    desktop)
      sudo nixos-rebuild switch --flake ~/dotfiles/#desktop --show-trace
      ;;
    macbook)
      sudo darwin-rebuild switch --flake ~/dotfiles/#macbook --show-trace
      ;;
    *)
      echo "Unconfigured device"
      ;;
  esac
}

if [ "$(uname -s)" = "Darwin" ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
eval "$(direnv hook zsh)"
