# Lines configured by zsh-newuser-install
HISTFILE=~/.local/state/histfile
HISTSIZE=10000
SAVEHIST=10000
bindkey -v
# End of lines configured by zsh-newuser-install

EDITOR=nvim
VISUAL=nvim

alias ls='ls --color=auto'
alias lg='lazygit'

# yazi with cd on exit
function y() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  yazi "$@" --cwd-file="$tmp"
  IFS= read -r -d '' cwd < "$tmp"
  [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
  rm -f -- "$tmp"
}

function rebuild() {
  case "$(uname -s)" in
    Linux)
      sudo nixos-rebuild switch --flake ~/.dotfiles/#thinkpad --show-trace
      ;;
    Darwin)
      sudo darwin-rebuild switch --flake ~/.dotfiles/#macbook --show-trace
      ;;
    *)
      echo "Unsupported platform"
      ;;
  esac
}

if [ "$(uname -s)" = "Darwin" ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
